name:                acknowledgments
version:             0.1.0.0
license:             LGPL
author:              ""
maintainer:          ""
copyright:           ""

#extra-source-files:
#- README.md

#description:         

dependencies:
- base >= 4.7 && < 5
- base-compat
- bytestring
- containers
- exceptions
- github
- text
- vector
- yaml >= 0.8.3

extra-deps:
- github >= 0.25

executables:
  acknowledgements:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
