name: 'issue closed'
on:
  issues:
    types: [closed]
  push:
    branches:
      - master

jobs:
  update-acknowledgments:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: Install cabal
        run: sudo apt-get install cabal-install
      - name: Update cabal
        run: cabal update
#      - name: Install hpack
#        run: cabal install hpack
      - name: Extract issues
        run: cd acknowledgments && cabal run > ../acknowledgments.txt # hpack && 
      - name: Upload acknowledgments.txt
        uses: actions/upload-artifact@v1
        with:
          name: acknowledgments
          path: acknowledgments.txt
