name: 'issue closed'
on:
  issues:
    types: [closed]
  push:
    branches:
      - master

jobs:
  update-acknowledgments:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        name: Cache ~/.cabal/packages
        with:
          path: ~/.cabal/packages
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
      - uses: actions/cache@v1
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
      - uses: actions/cache@v1
        name: Cache dist-newstyle
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-dist-newstyle
      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v1
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ '**/*.hs' }}
#      - name: Install cabal
#        run: sudo apt-get install cabal-install
#      - name: Update cabal
#        run: cabal update
#      - name: Install hpack
#        run: cabal install hpack
      - name: Extract issues
        run: cd acknowledgments && stack run > ../contributors.txt # hpack && 
      - name: Copy acknowledgments
        run: cp contributors.txt /home/runner/
      - name: Checkout the book's repo
        uses: actions/checkout@v2
        with:
          repository: 'lclem/problem_book'
          #path: 'somewhereelse'
          #fetch-depth: '0'
          token: ${{ secrets.ACCESS_TOKEN }}
#      - name: ls
#        run: cd ~ && ls -la && find . -type d
      - name: Copy acknowledgments
        run: cp /home/runner/contributors.txt .
      - name: Commit acknowledgments
        run: git add contributors.txt
      - name: Commit problem_book
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          #repository: 'lclem/problem_book'
          token: ${{ secrets.ACCESS_TOKEN }}
          commit_message: Update acknowledgments
      - name: Upload artifact contributors.txt
        uses: actions/upload-artifact@v1
        with:
          name: contributors
          path: contributors.txt
