name: 'issue closed'
on:
  issues:
    types: [closed]
  push:
    branches:
      - master

jobs:
  update-acknowledgments:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: Cache stack
        uses: actions/cache@v1
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }} #-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install cabal
        run: sudo apt-get install cabal-install
      - name: Update cabal
        run: cabal update
#      - name: Install hpack
#        run: cabal install hpack
      - name: Extract issues
        run: cd acknowledgments && stack run > ../acknowledgments.txt # hpack && 
      - name: Copy acknowledgments
        run: cp acknowledgments.txt /home/runner/
      - name: Checkout the book's repo
        uses: actions/checkout@v2
        with:
          repository: 'lclem/problem_book'
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Copy acknowledgments
        run: cp /home/runner/acknowledgments.txt .
      - name: Commit problem_book
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          #repository: 'lclem/problem_book'
          token: ${{ secrets.ACCESS_TOKEN }}
          commit_message: Update acknowledgments
      - name: Upload artifact acknowledgments.txt
        uses: actions/upload-artifact@v1
        with:
          name: acknowledgments
          path: acknowledgments.txt
