name: 'issue closed'
on:
  issues:
    types: [closed]
  push:
    branches:
      - master

jobs:
  update-acknowledgments:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: Install cabal
        run: sudo apt-get install ghc cabal-install
      - name: Update cabal
        run: cabal update
      - name: Install hpack
        run: cabal install hpack
      - name: Extract issues
        run: cd acknowledgments && hpack && cabal run > ../acknowledgments.txt
      - name: Upload acknowledgments.txt
        uses: actions/upload-artifact@v1
        with:
          name: acknowledgments
          path: acknowledgments.txt
